config/config.js, migrations/20191218025503-create-product.js, migrations/20191218031353-create-image.js, migrations/20191218035516-create-extra-item.js, migrations/20191218035516-create-gift.js, migrations/20191218040113-create-series.js, migrations/20191218040127-create-category.js, migrations/20191218040512-create-tag.js, migrations/20191218094003-create-tag-item.js, migrations/20191219083453-create-user.js, models/category.js, models/extraitem.js, models/gift.js, models/image.js, models/product.js, models/series.js, models/tag.js, models/tagItem.js, models/user.js, package-lock.json, package.json, test/models/Category.spec.js, test/models/Gift.spec.js, test/models/Image.spec.js, test/models/Product.spec.js, test/models/Series.spec.js, test/models/Tag.spec.js, test/models/TagItem.spec.js, test/models/User.spec.js, test/models/lib/testTools.js
建立 sequelize model 與 migration。
* Product
* Image
* Gift (特典 ExtraItem 更名為 Gift)
* Series
* Category
* Tag
* TagItem
這邊稍微調整了一下命名規則，不使用 sequelize 預設的小駝峰，更改為底線命名 (underscored)
之後統一命名規則為....
* model 統一使用小駝峰
* db table 統一使用底線
稍後會再把規格整理到 hackMD。
* 上述 6 個 model 都要存在
* model
* model 名稱應為大駝峰 (ex. Product, TagItem)
* model 屬性名稱應為小駝峰 (ex. createdAt)
* model 外鍵名稱應為大駝峰 (ex. SeriesId)
* table
* table 名稱應為底線 (ex. tag_items)
* table 欄位名稱英文底線 (ex. created_at, series_id)
* 關聯符合 ERD 圖 ( Product 與 Tag 應為多對多 )
=> 【Model】建立 sprint2 models

seeders/20191218080007-product-seeder.js, seeders/20191218114425-image-seeder.js, seeders/20191218121809-gift-seeder.js, seeders/20191218122338-category-seeder.js, seeders/20191218123353-series-seeder.js, seeders/20191218125001-tag-seeder.js, seeders/20191218130133-tagItem-seeder.js, seeders/20191218173542-user-seeder.js
建立 Seeder 資料
- Product
- Image
- Gift
- Series
- Category
- Tag
- TagItem
**公開日( release_date):** 
- 1-20 項商品設定在10月份公開
**預購期限( deadline):**   
- 1-10 設定在11月截止預約, 11-20 可預約至明年 1 月(預約中)
**發售日( sale_date):**      
- 1-5   設定在12月開始販售(販售中)
- 6-20 將在明年 2 月份販售
- 6-10 等待販售(下架狀態)
- 11-20 (預約中)
- Series: 鬼滅之刃、寶可夢、排球少年、Vocaloid
- Category: Figure、豆丁人、Figma、組裝模型(仮)
- Tag: 預購中、特典、庫存販售商品
=> 【Seeder】建立 sprint2  seeder

app.js, config/passport.js, controllers/userCtrller.js, lib/checker.js, middleware/auth.js, migrations/20191218162129-create-user.js, models/user.js, routes/admin/admin.js, routes/index.js, seeders/20191218172244-userSeeder.js, views/signin.hbs, views/signup.hbs
暫時先寫了User model與seeder，之後merge以Laster的model為主
建立table與寫入seeder：
```
sequelize db:migrate
sequelize db:seed:all
```
共新增三組帳號：
```
root@example.com //admin
user1@example.com //user
user2@example.com //user
password：12345678
```
```
http://localhost:3000/signup
```
- 可看到註冊頁面
- 可由此頁面註冊新使用者
```
http://localhost:3000/signin
```
- 可看到登入頁面
- 可輸入email和密碼進行登入
- 登入admin帳號會跳轉至 ```localhost:3000/admin/products``` 
- 登入非admin帳號會跳轉至 `localhost:3000/`
- 未登入/登入非admin帳號直接連至 `localhost:3000/admin`等admin路由會跳轉至`localhost:3000/`
```
http://localhost:3000/signout
```
- 登出使用者，跳轉至 `localhost:3000/`
=> basic使用者驗證系統

views/layouts/admin.hbs
- 移除admin layout的main.css引入
- 修改html title方便辨識
=> 【修正】admin layout錯誤引入main.css之問題

migrations/20191226032053-create-cart.js, migrations/20191226033558-create-cart-item.js, models/cart.js, models/cartitem.js, models/product.js
- models
- Cart
- CartItem
- migration
- create-cart
- create-cart-item
=> 【加入】購物車 model

controllers/admin/userCtrller.js, controllers/userCtrller.js, routes/admin/admin.js, routes/admin/index.js, routes/admin/products.js, routes/admin/users.js, routes/index.js, views/admin/products.hbs, views/admin/users.hbs, views/signup.hbs
- 完成後台會員資料頁面
- 比照後台商品頁面製作
- 預留訂單數量欄位供後期使用
- 地址較容易破壞版面且非重要資訊先不顯示出來
- CRUD等操作功能未製作
=> 【加入】後台會員資料頁面

app.js, routes/index.js
修正兩個合併後的問題
- `GET "/"` 已修復
- `GET "/cart"` 沒顯示購物車計數，已修復
=> 【debug】排除路由衝突

migrations/20191228134628-create-order.js, migrations/20191228141339-create-order-item.js, models/order.js, models/orderitem.js, models/product.js, models/user.js, seeders/20191228142243-order-seeder.js, seeders/20191228142301-orderItem-seeder.js, test/models/Cart.spec.js, test/models/CartItem.spec.js, test/models/Order.spec.js, test/models/OrderItem.spec.js, test/models/Product.spec.js, test/models/User.spec.js
- models
- Order
- OrderItem
- migration
- create-order
- create-order-item
- seeder
- Order seeder
- OrderItem seeder
=> 【加入】 Order相關model/seeder

controllers/cartCtrller.js, public/css/cart.css, public/css/main.css, public/js/cart.js, routes/cart.js, views/cart.hbs, views/partials/alert.hbs, views/partials/cartPageAlert.hbs
- 直接點選按紐增加購物車內的商品數量
- 直接點選按紐減少購物車內的商品數量
- 可直接入數量更新購物車內的商品數量
- 可刪除購物車內的商品
<br>
- 新增以下四個路由 ( 因與購物車相關，路由放置在 `/cart` 下 )
- `POST /cart/cartItem/:id/add`
- `POST /cart/cartItem/:id/sub`
- `POST /cart/cartItem/:id/update`
- `POST /cart/cartItem/:id/delete`
- 加入 cartPageAlert.hbs 提醒訊息
- 加入 public/js/cart.js，使更新商品功能，輸入框與 `<form>` 裡的 `<input>` 同步
- 點選購物車內 [ + ] 按紐
- 可以正常增加數量
- 當數量為 3 時，將無法再加增數量
- 如庫存不夠時，再按增加紐會跳出 alert 訊息，並把數量更新為目前庫存數
- 點選購物車內 [ - ] 按紐
- 可以正常減少數量
-  當數量為 1 時，將無法再減少數量
- 點選購物車內 [ 更新 ] 按紐
- 可以按照 input 的數量做更新
- 輸入的數量超過 3 樣時會即時顯示 `* 不可超過 3 樣` 紅字，並把數量更改為 3
- 更新時會確認庫存量，超過庫存時會跳出 alert 訊息，並把數量更新為目前庫存數
- 輸入的數 小於等於 0 ，將會跳出 alert 訊息，並把數量改為 1
- 點選購物車內 [ 刪除 ] 按紐
- 可以正常刪除商品
- 刪除商品後會跳出 alert 訊息
* 因還未與之前修改的 branch 合併，以下部分請忽略~
- seeder: cart、cartItem 還未刪除
- 購物車內無商品的文字 還未修改
=> 【加入】增減/刪除購物車商品數功能

public/css/main.css, public/js/main.js, views/layouts/main.hbs, views/partials/header.hbs, views/products.hbs
- 頁面向下滾動會觸發sticky效果
- sticky效果會將上方LOGO/登入/購物車隱藏
- 前台任一頁面的navbar皆會有sticky效果
- 將商品放入購物車的cart-alert不受影響，位於最上層
=> 【加入】Navbar sticky效果

public/css/main.css, public/js/main.js, views/partials/header.hbs
- navbar向上滾動時，會產生sticky效果
- sticky效果發生時，搜尋列會併入連結列左方
- 搜尋列與連結功能皆正常
=> 【優化】Navbar sticky效果

controllers/admin/seriesCtrller.js, public/css/admin/admin.css, routes/admin/index.js, routes/admin/series.js, views/admin/Series.hbs, views/layouts/admin.hbs
- 登入使用者帳號進入後台可以看到作品頁面
- 作品頁面可以看到目前資料庫中的所有作品
- 可以新增一筆作品
- 點選編輯作品，作品名稱會帶入上方input欄位
- 點擊更新作品按鈕後，會更新作品並重新導向回所有作品
- 點選刪除作品按鈕，會跳出modal再次確認
- 點選確認刪除，會刪除該作品並重新導向回所有作品
- 新增與編輯功能有前後端防空白功能
=> 【加入】後台Series CRUD功能

.env.example, .gitignore, config/newebpay.js, controllers/orderCtrller.js, controllers/userCtrller.js, lib/tools.js, middleware/auth.js, migrations/20191228134628-create-order.js, migrations/20200109153129-create-payment.js, models/order.js, models/payment.js, public/css/profile.css, routes/index.js, routes/orders.js, routes/users.js, seeders/20191228142243-order-seeder.js, test/models/Order.spec.js, test/models/Payment.spec.js, views/orders.hbs, views/payment.hbs, views/profile.hbs
串接第三方支付系統，藍新 API。
- Order model
- sn 欄位追加設定 unique key (唯一)
- 追加欄位 orderNo，用作串金流的識別 flag
- Order seeder，使假資料皆為未付款狀態
- 加入 Payment Model
- 應該不用做 Payment 的 seeder?
- status，布林，付款成功 or 失敗
- code，字串，紀錄藍新狀態碼，成功時一律為 `"SUCCESS"`
- msg，字串，紀錄藍新失敗訊息
- trade_no，字串，紀錄藍新交易序號
- order_no，字串，紀錄我方 post 給藍新的識別碼
- pay_time，Date，紀錄支付完成的寶貴瞬間
- 路由 `/users/orders` 調整為 `/orders`，並更改全部相關連結
- 比照串金流教材最後一個影片，建立 file `.env.example` 用作 `.env` 範例
**※ 需先重刷 migration**
**※ 如需要藍新金流的帳戶資訊，可參看 sprint 1 看板**
- `.env` 要追加環境變數 (HOST 以外，數值參看 sprint 1 看板)
- HOST_URL
- MERCHANT_ID
- HASH_KEY
- HASH_IV
<br>
- HOST_URL 需優過輔助軟體 `ngrok` 設定
- 可參考課程 U197
- 至 [ngrok 官網](https://ngrok.com/)，下載 `ngrok.exe`，放到專案目錄 (git 不追蹤)
- 需要註冊帳號
開啟新的終端機視窗，專案目錄下輸入指令啟動。
```
$ ngrok http 3000
```
啟動後，複製 https 的網址，貼到 `.env` 的 HOST_URL。
**※ 之後不使用 …
=> 【加入】串金流，線上支付功能

routes/users.js
- 修正註冊時會跑出錯誤訊息 `Cannot POST /users/signup` ，無法成功導回正常頁面。
- 在 routes/users.js 加上 **(req, res) => res.redirect('/products')**
`router.post('/signup', userCtrller.signUp, userCtrller.signIn, (req, res) => res.redirect('/products'))`
- 註冊完後可以正常導回所有商品頁
=> 【debug】註冊後無法成功導向

controllers/orderCtrller.js, public/css/main.css, views/partials/alert.hbs
- 從 Order 查詢此筆訂單的商品，更新庫存 (扣掉購買的數量)
- 訂單成立時，商品庫存會成功扣除所購買的數量 (從 workbench 確認)
=> 【加入】訂單成立時扣除庫存數

public/css/admin/orders.css, views/layouts/admin.hbs, views/partials/header.hbs
修復 sticky 分類bar。
現在前台 sticky bar 已能正常工作。
並替換後台 Logo。
=> 【修改】修復 sticky 分類bar

README.md
加入第一版 README 說明文件。
https://github.com/Lastor-Chen/greatsmile/tree/readme
=> 【加入】 README

config/passport.js, controllers/admin/orderCtrller.js, controllers/userCtrller.js, migrations/20191219083453-create-user.js, models/user.js, routes/admin/orders.js, seeders/20191218173542-user-seeder.js, test/models/User.spec.js, views/admin/categories.hbs, views/admin/orders.hbs, views/admin/prodEdit.hbs, views/admin/prodNew.hbs, views/admin/series.hbs, views/admin/tags.hbs, views/admin/users.hbs, views/partials/signUp.hbs
- 後台訂單頁面，出貨狀態改為表單按鈕，可以任意點擊變更出貨狀態
- 進入後台/訂單頁面，點擊未取消的訂單出貨狀態可以切換為已出貨/未出貨
- post後會導回`/admin/orders?mode=uncancel`顯示未取消訂單一覽
- 已取消的訂單無法切換出貨狀態
=> 【加入】 後台訂單切換出貨狀態

README.md
如題，更新 ReadMe。
- ReadMe 相關資料，追加路由設計表
- ReadMe 尾巴，追加心得 Blog 連結
=> 【更新】ReadMe 追加 ERD 與心得Blog

views/product.hbs
- 修改麵包屑的連結導向
- 確認詳細商品頁的麵包屑可以導向正確分類
=> 【fix】 麵包屑未正常導向
