controllers/prodCtrller.js
migrations/20191218031353-create-image.js
models/image.js
package.json
public/css/main.css
public/css/product.css
routes/products.js
seeders/20191218080007-product-seeder.js
seeders/20191218114425-image-seeder.js
seeders/20191218121809-gift-seeder.js
seeders/20191218125001-tag-seeder.js
seeders/20191218130133-tagItem-seeder.js
views/layouts/main.hbs
views/partials/header.hbs
views/product.hbs

`GET /products/:id`  商品詳細頁面。
UI 跟資料顯示先搞定。
**branch 主要內容**
- 實裝 product 詳細頁面
- 修改 seeder
- Image 商品圖尺寸固定為 530x670
- Image 各商品必只有一張圖為 main img
- id 1 的商品，必有 7 張圖 (方便畫廊 UI 調整 width)
- id 2 的商品，無庫存
- 只有前 5 項商品有特典
- "特典" 更名為 "附特典"
- 修改 Image table 欄位，加入 is_main (model 屬性為 isMain)
- 引入套件 momentjs 處理 Date
<br>
● UI 相關
- 頁面符合 Wireframe
- 右上方購物車 UI 有調整，目前與 Wireframe 不同
- 畫廊的放大鏡按鈕，等實裝畫廊再考慮放不放
- 畫廊預設顯示的大圖為 Image isMain 圖片，根據 seeder 此圖必為貓
- 畫廊與特典圖片，目前有給上灰色背景暗示有內容，防止假圖 API 抓圖失敗
<br>
● 依 Product 資料產生改變
- id > 5 為無特典商品，應不顯示特典 Tag 與下方特典區塊
- id < 10 商品為發售中
- 發售中商品，購物車下方應顯示「發售中」
- 發售中商品「受理期間」區塊，應出現刪除線與 ※ 註記內容
- 預約中商品，購物車下方應顯示「預約中」
- 預約中商品「受理期間」區塊，應沒有刪除線與 ※ 註記內容
- id 2 商品為已售完，購物商按鈕應被禁用，下方顯示「已售完」
<br>
● 其他註記
- 右上方 Tag 僅會顯示 「附特典」，不顯示其他 Tag
- 回Top 按鈕未實裝
- 價格顯示一律都有位數 dots，ex. NT 10,000
- 受理期間與公告日會顯示星期幾，ex. (四) …

【頁面】加入 Product 詳細頁面 (畫廊未實裝)

---

controllers/prodCtrller.js
migrations/20191218031353-create-image.js
models/image.js
package.json
public/css/main.css
public/css/product.css
public/js/main.js
routes/products.js
seeders/20191218080007-product-seeder.js
seeders/20191218114425-image-seeder.js
seeders/20191218121809-gift-seeder.js
seeders/20191218125001-tag-seeder.js
seeders/20191218130133-tagItem-seeder.js
views/layouts/main.hbs
views/partials/header.hbs
views/product.hbs

實裝 back to top 按鈕，於畫面右下角。
html 放置於 main layout <footer> 內。
※ 因為需要使用 jquery 的 animate 功能，有重新引入 jquery 套件。
bootstrap 預設使用 slim(輕量) 版本的 jquery，這邊將其改為完全版 jquery，
並順便更新 bootstrap 整組 script 套件，從 v4.3.1 變為 v4.4.1。
可利用 `GET "/products/:id"` 商品詳細頁測試。
- 位於頂部時，按鈕不會出現
- 往下捲動約 500px 才會出現按鈕
- 按下後有向上滾動回去的特效，而不是秒切

【加入】back to top 按鈕

---

controllers/prodCtrller.js
public/css/main.css
public/js/products.js
routes/index.js
views/home.hbs
views/layouts/main.hbs
views/partials/header.hbs
views/product.hbs
views/products.hbs

search 功能預期前台全頁面都會使用，
在每個 controller 都寫 search 的程式碼，不太科學。
故，開了個 `"/search"` 的路由，controller 與 products 共用 `getProducts`。
頁面也是共用 `products.hbs`
- 加入 search feature。
- 開通 route `GET /search`
- 為了方便操作，建立陽春首頁 home.hbs
<br>
- 在任何頁面都能使用 search
- 搜尋後，路由應該變為 `/search?q=內文`
- 麵包屑變為 `Home > 搜尋商品`
- 搜尋後，會保留 input 值
- 可以透過商品名稱搜尋
- 直接從資料庫複製 Product.name 搜尋測試
- 可以搜尋到所有「包含」該關鍵字的商品 (模糊比對)
- 可以透過作品名稱搜尋
- 直接從資料庫複製 Series.name 搜尋測試
- 應為模糊比對
- 查無結果時
- 頁面應該只會出現麵包屑跟提示文字
- footer 應該置底
- 搜尋後，可以保持搜尋結果，進一步使用排序功能
- 可以透過網址的 query string 確認排序與搜尋是否同時存在
- 搜尋的 query string 比照 Youtube 與 Google 命名為 `q`

【加入】search 功能

---

controllers/prodCtrller.js
public/css/product.css
public/js/product.js
seeders/20191218114425-image-seeder.js
views/layouts/main.hbs
views/product.hbs

商品詳細頁，加入畫廊展示與燈箱展示功能。
- slick-carousel (畫廊)
- lightbox2 (燈箱)
<s>
目前假資料的圖片是對 lorempixel.com 用 url 打 API 要圖，
燈箱效果再開啟時會再發一次該 url，導致會生成不同的隨機圖片。
所以目前燈箱出現不同圖片，屬正常現象。
</s>
<br>
<br>
- 有製作簡易 RWD，視窗縮小時，畫廊按鈕不會爆版。
- click 左 / 右 按鈕，可以切換圖片。
- 切換圖片時，下方的小圖片 list 能正確對應到大圖。
- 下方的圖片 list，會高亮顯示當前圖片。 (這不是原本套件的功能，研究了一陣子......)
- click 大圖可以開啟 lightbox，並能正常工作。
- <s>如上述所提，不只圖片會隨機到別張，而且等 lorempixel 回應，會等超久......</s>
<s>
建議燈箱測試時，把 Image seeder 改一下，
把兩個 url 屬性值，改成指定圖片 id 跟 lorempixel 要圖。
重刷 seeder 之後再來測燈箱。
</s>
<pre>
<s>url: `http://lorempixel.com/530/670/cats/${index + 1}`
url: `http://lorempixel.com/530/670/food/${index + 1}`</s>
</pre>
<s>測完之後記得把 seeder 改回來，因為 lorempixel 實際有的圖片 id 好像沒那麼多。
這樣後面的其他商品，假圖會沒東西。</s>

【加入】product 畫廊展示功能

---

controllers/admin/prodCtrller.js
models/image.js
package.json
public/css/admin.css
routes/admin/admin.js
views/admin/new.hbs
views/admin/products.hbs
views/layouts/admin.hbs

`GET /admin/products`頁面實作
- 管理者登入後可以直接進到`/admin/products`商品總覽頁面
- 頁面各欄位可以進行排序
- search bar可以針對欄位進行關鍵字搜尋
- 點擊商品照片或名稱可以另開分頁連至前台該商品詳細頁面
- 若商品沒有圖片會顯示no image圖示
- 發售狀態以當日做邏輯判斷顯示是否已發售
- 上架欄位會依照狀態顯示O或X
- 上架欄位會因狀態切換表單路由`POST /admin/products/:id/display`或`POST /admin/products/:id/undisplay`
- 編輯商品圖示會連至`/admin/products/:id/edit`
- 詳細資訊圖示會連至`/admin/products/:id`
- 刪除圖示會觸發modal確認是否刪除該商品(刪除功能尚未實作)
- 分頁功能可依照不同排序/搜尋顯示
- 後台似乎不需要前台的main layout，待討論
- 商品的相關屬性很多，全部列出畫面會很擁擠(現在也是)，看有沒有其他建議？

【頁面】後台商品總覽

---

controllers/admin/prodCtrller.js
package-lock.json
package.json
public/css/adminAdd.css
routes/admin/admin.js
views/admin/edit.hbs
views/admin/new.hbs
views/admin/products.hbs
views/layouts/admin.hbs

`npm i`
- imgur
- multer
- `.env`加入IMGUR_CLIENT_ID，須自行新增在本地端
- 已放在trello > sprint 1> 資料暫存區> .env
- 可以從nav bar進入新增商品頁面
- 在新增商品頁面中新增一項商品
- 新增過程中可以選擇多張圖片上傳
- 新增完畢後導回後台商品一覽頁面
- 確認第一張選擇上傳的照片為mainImg
- 尚未有表單驗證功能(之後連同alert message一起追加)
- 可點擊上架狀態欄位的圖示變更上架/下架狀態
- 上下架狀態亦可於新增商品/編輯商品做修改
- 點擊商品編輯圖示可以連至編輯頁面
- 可於編輯頁面修改商品資訊
- 可以上傳新商品圖片
- 可以重新指定mainImg
- 送出後會導回後台商品一覽頁面
- 後台商品一覽頁面可以顯示修改後的資訊
- 點擊詳細圖示可以開啟modal顯示詳細資訊
- 可從modal連至商品編輯頁面
- 版面等待靈感重新設計...求建議XD
- 點擊刪除按鈕會跳出確認modal
- 再次點擊確認刪除可以刪除該商品

【加入】後台商品頁CRUD功能

---

app.js
controllers/orderCtrller.js
lib/hbs_helpers.js
public/css/address.css
public/css/cart.css
public/css/main.css
routes/index.js
routes/order.js
views/address.hbs
views/cart.hbs

結帳流程1之地址輸入 UI 頁面。
表單功能尚未實裝。
- 路由暫定為 `GET "/order"`，並可由購物車頁面點選結帳按鈕進入
- 使用者無領取購物車時，無法進入
- 使用者有購物車，但無放入商品時無法進入 (可透過資料庫手動刪除 CartItem 測試)
- UI 及相關文字目前比照好微笑，有想法可提出
- 側邊攔合計與商品 List 已實裝
- 能正確顯示購物車內所有商品
- 商品單價 x 個數的計算應正確
- 上方合計價格應正確
- 調整了 `main.css` 分類選單的樣式，使 Bootstrap 客製化內容只限定在分類Bar作用
- 追加 hbs helper `addDot`，可直接在 hbs 將價格數字加上 dots，使後端邏輯不用在意型別問題
- `app.js` 之 session 設定，延長存活時間，從 80s 延至 10min

【加入】checkout 結帳頁1、地址

---

app.js
controllers/orderCtrller.js
lib/hbs_helpers.js
public/css/address.css
public/css/delivery.css
public/css/main.css
routes/index.js
routes/order.js
views/address.hbs
views/cart.hbs
views/delivery.hbs

完成交貨方式選擇頁面之 UI 切版。
- 可從結帳頁-1，地址頁面，按「下一步」 GET 交貨頁
- 側邊攔能正確顯示購物車內商品
- controller 內容基本是 adress 頁直接複製貼上，側邊攔應該沒問題
- 合計部分，追加運費，目前先綁死「宅配」 NTD 150
- (好微笑，並不會隨著選擇改變選擇，即時重新計算運費)
- 目前合計數字為，小計 + $150

【加入】結帳頁-2、delivery 交貨頁

---

controllers/orderCtrller.js
lib/hbs_helpers.js
public/css/view.css
routes/index.js
routes/order.js
views/view.hbs

結帳流程4 之最後訂單檢視 UI 頁面。
表單功能尚未實裝。
- 路由暫定為 GET "/order/view"
- 側邊欄為之前結帳頁 1 的內容
- 加入了運費的變數
- 新增側邊欄結帳按鈕
- 已先加入 hbs_helpers.js addDot 讓金額顯示正確格式
- 購買者資訊目前都是寫死的，之後會再修改
- 編輯按鈕可以連到相對應的頁面
- 送貨地址 `/order`
- 送貨選項 `/order/delivery-method`
- 付款詳細資料 `/order/pay-method`

【加入】checkout 結帳頁4、最後檢視

---

app.js
controllers/userCtrller.js
models/product.js
public/css/main.css
public/css/profile.css
routes/users.js
views/orders.hbs
views/partials/header.hbs
views/profile.hbs

- navbar動線
- 使用者帳戶頁
- 使用者訂單頁
- 未登入狀態下，直接連至`/users/profile`或`/users/orders`會被導回登入頁面
- 使用者(非root)登入後，navber會顯示進入使用者帳戶頁之動線
- 點擊該按鈕可進入到使用者頁面
- 點選主卡片或側邊欄的"訂購紀錄"皆可連結至使用者訂單頁面
- 訂單頁面僅會顯示登入使用者的訂單資訊且資訊正確
- 每筆訂單可以按下後方的訂單內容按鈕來展開/收納收件資訊與出貨資訊
- 使用者無訂購紀錄時會顯示提示訊息
- 歡迎各種版面與色彩建議QQ

【加入】使用者帳戶/訂單頁 

---

controllers/admin/tagCtrller.js
public/css/admin/admin.css
routes/admin/index.js
routes/admin/tags.js
views/admin/tags.hbs
views/layouts/admin.hbs

- 登入使用者帳號進入後台可以看到標籤頁面
- 標籤頁面可以看到目前資料庫中的所有標籤
- 可以新增一筆標籤
- 點選編輯標籤，標籤名稱會帶入上方input欄位
- 點擊更新標籤按鈕後，會更新標籤並重新導向回所有標籤
- 點選刪除標籤按鈕，會跳出modal再次確認
- 點選確認刪除，會刪除該標籤並重新導向回所有標籤
- 新增與編輯功能有前後端防空白功能

【加入】後台Tag CRUD功能

---

controllers/admin/categoryCtrller.js
public/css/admin/admin.css
routes/admin/categories.js
routes/admin/index.js
views/admin/categories.hbs
views/layouts/admin.hbs

- 登入使用者帳號進入後台可以看到分類頁面
- 分類頁面可以看到目前資料庫中的所有分類
- 可以新增一筆分類
- 點選編輯分類，分類名稱會帶入上方input欄位
- 點擊更新分類按鈕後，會更新分類並重新導向回所有分類
- 點選刪除分類按鈕，會跳出modal再次確認
- 點選確認刪除，會刪除該分類並重新導向回所有分類
- 新增與編輯功能有前後端防空白功能

【加入】後台category CRUD功能

---

controllers/orderCtrller.js
package-lock.json
package.json

結帳頁，提交成立訂單後，發送通知信給會員。
※ 需在 `.env` 加入 Gamil 帳密資料，已放到看板 sprint 1 裡面。
※ 需先安裝套建 `$ npm i nodemailer`
※ 請不要頻繁測試寄信，好像會被鎖。
1. 建立新帳號，輸入確實存在的 Email 帳戶
2. 完成結帳頁表單送出後，可在終端機看到 sent Email 之 console.log 訊息
3. 去信箱確認有沒有信 (有時候需要等一下)
信件內容有空再優化。

【加入】 訂單成立後，發送 Email 功能

---

controllers/admin/prodCtrller.js
views/admin/products.hbs

- 後台商品詳細頁新增 Tag 欄
- 調整商品詳細頁 UI
因商品內文實際上內容很多，所以目前調整為以下樣式~

【加入】後台商品詳細頁 Tag

---

.env.example
.gitignore
config/newebpay.js
controllers/orderCtrller.js
controllers/userCtrller.js
lib/tools.js
middleware/auth.js
migrations/20191228134628-create-order.js
migrations/20200109153129-create-payment.js
models/order.js
models/payment.js
public/css/main.css
public/css/profile.css
routes/index.js
routes/orders.js
routes/users.js
seeders/20191228142243-order-seeder.js
test/models/Order.spec.js
test/models/Payment.spec.js
views/orders.hbs
views/payment.hbs
views/profile.hbs

- 追加寄件方式欄位
- 修改下方訂單商品總覽頁面排版
- 商品有特典時顯示特典icon
- 清單上會附上各商品下定時金額、數量與相乘的價錢
- 總金額有加上運費計算
- 金額統一採用addDot格式化
- 訂單商品一覽的價錢與數量是否與資料庫中相同
- 含有特點之商品可以正確顯示icon
- 商品圖片與名稱可以連結到該product頁面
- 重新發送確認信 (待此PR merge後)
- 取消訂單
- 編輯收件地址
- 顯示帳單地址
- 顯示支付期限

【優化】前台使用者訂單一覽

---

controllers/prodCtrller.js
controllers/userCtrller.js
middleware/auth.js
public/css/main.css
public/css/product.css
public/css/products.css
public/css/sign.css
routes/users.js
seeders/20191218121809-gift-seeder.js
views/cart.hbs
views/checkout_1.hbs
views/checkout_2.hbs
views/checkout_3.hbs
views/checkout_4.hbs
views/layouts/main.hbs
views/orders.hbs
views/partials/header.hbs
views/partials/signIn.hbs
views/partials/signUp.hbs
views/product.hbs
views/products.hbs
views/profile.hbs
views/sign.hbs
views/success.hbs

前台 container 加寬至 1250px，並配合調整前台各頁面。
Gift seeder，調整假圖片為 picsum API。
前台頁面的 Bootstrap `col-md` 都拿掉了，統一採用 scale 的做法。
部分頁面有保留 RWD 流動。
- 前台各頁面，視窗小於 1250px 時，會整體縮小
- product 詳細頁、success 頁有局部 RWD 流動
- products 型錄頁，讓 card 變圓胖
- sign 頁、profile 頁、orders 頁，UI 無明顯問題
- cart 頁、checkout 各頁、success 頁，UI 無明顯問題
- cart 頁按「前往結帳」，可以導入 '/users/signin/checkout' (登入在左邊)
- 於此頁登入，會直接進入 checkout 頁
- 只有 product 詳細頁，會引入畫廊套件

【修改】layout container 寬度

---

controllers/admin/prodCtrller.js
public/js/admin/product.js
views/admin/edit.hbs
views/admin/new.hbs
views/layouts/admin.hbs

- 後台新增/編輯產品時，上傳圖片可以顯示已選擇的圖片
- 可同時選取多張一併顯示
- 新增商品頁面，選擇圖片後可以看到即時預覽出現並正常新增商品圖片
- 編輯商品頁面，選擇圖片後可以看到即時預覽出現並正常更新商品圖片
- 圖片選擇較多時有warp效果換行排列
- 要刪除未上傳的特定檔案似乎有點麻煩

【加入】後台產品上傳前預覽圖片

---

views/cart.hbs

- 移動`刪除/更新`按鈕到數量鍵下方
- 更新`商品價格/商品數量/合計價格`排版方式，解決因調整數量造成的抖動問題
- 於購物車放入商品後進入購物車頁，觀察排版是否如上圖所示
- 刪除與更新按鈕可以正常運作
- 調整商品數量時不會使排版有移動

【優化】購物車頁UI/UX更新

---

controllers/admin/paymentCtrller.js
routes/admin/index.js
routes/admin/payments.js
views/admin/payments.hbs
views/layouts/admin.hbs

- 後台交易紀錄頁 UI
- 搜尋交易紀錄功能
- 因欄位較少，所以把欄位增減功能拿掉了
- 後台 navbar 加入 `交易紀錄` 選項
- 管理者可以輸入 SN 或是 order_id 來搜尋訂單紀錄
- 有紀錄時可以看到此筆訂單交易紀錄
- 搜尋不到時，將會顯示 alert
- 保留 alert 的位置，使下面表單不會隨著 alert 的顯示移動
- 時間格式需顯示日期 + 時間 (不確定需不需要到秒)
- 原本想讓搜尋不到紀錄時，跳回去還能顯示搜尋的SN，有使用 req.flash，但一直沒成功

【加入】後台交易紀錄頁面及搜尋功能

---

controllers/orderCtrller.js
views/orders.hbs
views/success.hbs

- 訂單成功頁會有 `繼續購物` `立即付款` 的按鈕
- 點選 `立即付款` 會被導到藍新結帳頁
- 使用者訂單頁可以直接看到訂單是否付款

【加入】訂單成功頁加入立即付款按鈕

---

controllers/admin/giftCtrller.js
public/js/upload.js
routes/admin/gifts.js
routes/admin/index.js
views/admin/Series.hbs
views/admin/categories.hbs
views/admin/gifts.hbs
views/admin/tags.hbs
views/layouts/admin.hbs

- 完成特典在後台的CRUD
- admin帳號進入後台後，可以點擊特典連結瀏覽所有特典
- 表格上方可以新增一筆特典，可輸入名稱與上傳圖檔(限一張)
- 圖檔非必填
- 名稱有後端防空白
- 點擊上傳按鈕可以展開檔案選擇視窗
- 選擇圖片後，按鈕左側會出現預覽畫面
- 點擊一筆特典的編輯按鈕，會展開編輯欄位
- 可以重新上傳特典圖片(預覽尚未實作，還在看array.change的方法...)
- 可以重新編輯特典名稱
- 按下刪除按鈕可以刪除特典
- admin/product 的新增與編輯要增加選擇特典的功能

【加入】後台特典CRUD

---

config/passport.js
controllers/cartCtrller.js
controllers/prodCtrller.js
controllers/userCtrller.js
middleware/auth.js
migrations/20191226032053-create-cart.js
models/cart.js
public/css/main.css
public/css/product.css
public/css/products.css
public/css/sign.css
routes/users.js
seeders/20191218121809-gift-seeder.js
views/cart.hbs
views/checkout_1.hbs
views/checkout_2.hbs
views/checkout_3.hbs
views/checkout_4.hbs
views/layouts/main.hbs
views/orders.hbs
views/partials/alert.hbs
views/partials/header.hbs
views/partials/signIn.hbs
views/partials/signUp.hbs
views/product.hbs
views/products.hbs
views/profile.hbs
views/sign.hbs
views/success.hbs

使購物車，區分出「User車」與「 訪客車」。
並於登入時，合併訪客車商品，至 User 車。
登入後，會有合併提示，如上圖。
**※ 記得刷新 migration**
- Cart model，追加欄位 `UserId` (資料庫為 `user_id`)
- passport 本地戰略，登入 function 優化
- 調整為 `async / await` 格式
- 反序列時，User 不 include 其他 table
登入時，有分為 User 原本有車/無車，訪客有車/無車，排列組合共 4 種情況。
測試時，建議在 `app.js` 添加以下 console.log，檢視「當前購物車」與「user 登入狀態」。
並搭配資料庫檢查 Cart、CartItem。
<pre>
app.use((req, res, next) => {
console.log('\n' + `${req.method} ${req.path}`)
<b>console.log(`cartId`, req.session.cartId)  // add this</b>
<b>console.log('user', req.user && req.user.id)  // add this</b>
// 原本其他的 code...
}
</pre>
- 登入後，應該導入 `/cart`
- 登入失敗時，仍舊可回到 `/users/signin` or `/users/signin/checkout`
- User 車，原本有商品時，顯示商品合併提示 
- 登出後，會歸還購物車，console.log `cartId` 變為 undefined (session 被清除)
<br>
- 未登入時，將商品加入購物車，資料庫 Cart 的 `user_id` 應為 null
<br>
- 該 …

【加入】User 綁定購物車

---

controllers/prodCtrller.js
middleware/tag.js
routes/index.js
views/products.hbs

- 前台 Tag 與資料庫建立關聯
- 除了 `所有商品`  和 `即將截止預購` 是綁死的，其他都為自動帶入
- 建立 tag 的中間件 `/middleware /tag.js`
- /products、/search 兩個路由引入中間件
- /products 路由
- /search 路由
以上兩個路由都應可顯示標籤，新增標籤時也應能成功帶入。

【加入】前台 tag 關聯資料庫

---

controllers/prodCtrller.js
lib/product_tools.js
lib/tools.js
views/partials/header.hbs
views/products.hbs

getProducts 太大包，將其進行拆分，
並優化部分 code，減少整體行數。
效能本身沒進行優化，
只是將 code 做成 function 搬出去而已。
- 將 getProducts 部分 code 拆成 function，放到 `lib/product_toos.js`
- 將遠本在 `lib/tools.js` 的 genQueryString，搬移到 `lib/product_toos.js`
- pageLimit 應該是常數，於是更名為 PAGE_LIMIT
- category 與 tag，原本使用 name 來 query，現在改用 id
- 前台 getProducts controller，code 長度縮減成約 1.5 個螢幕長
- 分類、搜尋、Tag、排序、分頁等功能，皆能正常工作，沒有壞掉
- 不用太詳細的去對篩選出來的商品正不正確，因為 code 本身其實沒變動

【重構】前台 getProducts

---

controllers/admin/giftCtrller.js
views/admin/gifts.hbs

- 後台特典頁面，編輯特典時可以加入關聯的商品id
- 新增一筆特典，展開其編輯欄位後會顯示空白的商品欄位
- 商品欄位可以寫入商品id並更新
- 商品欄位若清空並更新，會將該特典的productId清空為null
- 若寫入的商品id不存在，後端會阻擋寫入並回傳提示

【加入】後台特典關聯商品之功能

---

controllers/admin/prodCtrller.js
views/admin/products.hbs

- 商品詳細頁面加入特典資訊
- 有特典會顯示特典名稱
- 若無特典會顯示`無`
- 商品詳細頁面加入相關日期資訊
- 公開日期
- 預購截止日期 (顯示為預購截止統一四個字)
- 發售日期

【加入】後台商品詳細頁面更新

---

controllers/orderCtrller.js

結帳 checkout 時，防止使用者跳過表單，直接進行提交。
順便修改建立訂單時，儲存的收件人姓 + 名格式，由「逗號」改為空一格。
- 從 `/cart` 開始結帳後，無法直接網址輸入 `GET /orders/checkout_4` 等，進入後面表單
- 只能經過正規途徑，POST 表單，才能進入下一頁
- 不當訪問後，可以導回原本的頁面繼續進行，checkout 系統應不會壞掉
<br>
- 未填寫完所有表單時，應無法 `POST /orders`
- 會被導回購物車頁，並顯示「錯誤訪問」
測試方法，在 checkout 途中的頁面，從瀏覽器輸入已下指令進行 POST。
```
$.post('/orders', function (data) {
document
.open('text/html', 'replace')
.write(data)
})
```
- 訂單成立後，收件人姓名應為 `姓氏 名`，中間空一格，而非逗號

【debug】防止 checkout 時跳過表單

---

controllers/prodCtrller.js
lib/product_tools.js
views/product.hbs
views/products.hbs

重建前台商品，顯示邏輯。
現在前台不會顯示 deadline ~ saleDate 之間，處於「等待發售」的商品。
為了確認方便，前台加入了提示機制，commit 為：
[加入] 前台商品能顯示「預約截止」提示
請先 checkout 到該 commit，依照我們目前的 seeder 資料，
應該有些商品已過了 deadline，但 tag 仍為「預購中」，
該類商品應該會出現下圖的情況：
先將 commit 切回最新
- 製品一覽，點選 Tag「預購中」，應不會出現「預約已截止」商品
- 製品一覽，點選 Tag 「即將截止預約」 ，應不會出現「預約已截止」商品
- 即將截止預約，篩選邏輯改由純靠 deadline 判斷，而不判斷「預約中」 Tag
- 將其中一件商品的預約中 tag 拔掉，應該仍然可以被篩選出來
- 可輸入下方 MySQL 雙重比對，出現的商品應該大致相同 (time計算問題，會有一兩件誤差)
```
SELECT products.id, products.deadline, products.sale_date, tags.name FROM products
LEFT JOIN tag_items AS items ON products.id = items.product_id
LEFT JOIN tags ON items.tag_id = tags.id
WHERE deadline between NOW() AND NOW() + interval 7 day;
```

【修改】Tag，前台商品顯示邏輯

---

controllers/admin/paymentCtrller.js
controllers/admin/prodCtrller.js
controllers/orderCtrller.js
controllers/prodCtrller.js

使用 `moment-timezone`，將後端有使用 `moment().format()` 整理時間的部分，
皆指定為台北時區 `moment().tz('Asia/Taipei').format()`。
修復藍新金流，payTime 誤存成國際標準時間的錯誤。
移除了串金流頁，測試確認用的 console.log。
先將自己的電腦時區，改成 +00:00 國際標準時間。
- 訂單成功頁，顯示的訂單成立時間，應為台北時間。
- 串金流付款後，資料庫紀錄的 pay_time，應為台北時間，而不會多 8 小時。
- 後台該筆 payment 顯示的付款時間，應為台北時間。

【debug】修復 heroku 時區問題

---

.env.example
app.js
controllers/cartCtrller.js
routes/admin/products.js

- 修復後台商品 preview 頁，分類bar消失的問題
- 更改 session 設定方式 (dotenv)
session 設定改設在環境變數，並更動了密碼。
已將新密碼放在看板 sprint 1 資料存放區。
- 現在後台商品 preview 應能正常顯示分類bar
- 添加 session 設定進 .env 後，能正常登入、操作購物車
- `.env.example` 有新增 session 設定範例

【fix】修復後台商品預覽，分類bar

---

controllers/orderCtrller.js
lib/order_helper.js
routes/index.js

- 扣庫存、建Order、建OrderItem、刪CartItem，整套改用 transaction
- 並將此區塊拆分到 `lib/order_helper.js`
- 檢查庫存的部份，也拆分到 `lib/order_helper.js`
- 精簡「防不當進入」區塊的 code
幫 postOrder 瘦了一圈。 
嘗試使用之前 demo 時，業界評審 Mat 提到的 transaction 來改寫。
這東西概念很簡單，[sequelize](https://sequelize.org/master/manual/transactions.html) 已經包好 function 了，大概這種感覺。
```
sequelize.transaction(async t => {
// 扣庫存
// 建立 Order
// 建立 OrderItem
})
```
只要有一個失敗，就會全部還原。
但是我們設計上，希望能回傳「哪件商品」、「庫存剩多少」給使用者，
而 transaction 如果因庫存不夠失敗，只會回傳錯誤訊息，並不會返回該 product 的 data。
所以「檢查庫存」的地方，其實還是得用原本的寫法。
- 結帳流程應該沒有壞掉
- 加入購物車後，故意從資料庫減少庫存，使其小於購買數量
- 最終確認時，會被彈回，並返回庫存不夠的商品訊息給 User
ps. transaction 的測試比較麻煩，我這邊確認過了，應該沒問題

【重構】postOrder 改用 transaction 機制
